### ISSUE TITLE
Debug test app provider test output:

### ISSUE THREAD

**Issue by chrislawlor** [pymetrics/pact-testgen#12]
cd into `test_app/provider`, and run `python manage.py test` (may need to install some dependencies, like Django):

```
pact-testgen/test_app/provider on  master $! 🐍 v3.7.11 (pact-testgen)on ☁️ lawlor.chris@gmail.com 
❯ python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.EEEEEE
======================================================================
ERROR: test_test_a_book_search_request_for_author_id_1 (tests.test_pact.Test_a_book_exists_with_author_id_1_an_author_with_id_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/clawlor/code/pact-testgen/test_app/provider/tests/test_pact.py", line 116, in test_test_a_book_search_request_for_author_id_1
    success = verify_response("LibraryClient", "Library", expected, actual)
  File "/home/clawlor/code/pact-testgen/pact_testgen/verify.py", line 21, in verify_response
    verifier = ResponseVerifier(pactman_pact, pact_response.dict(exclude_none=True), result)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/pactman/verifier/verify.py", line 231, in __init__
    self.matching_rules = rule_matchers_v2(rules)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/pactman/verifier/matching_rule.py", line 334, in rule_matchers_v2
    section = split[1]
IndexError: list index out of range

======================================================================
ERROR: test_test_an_author_deletion_request (tests.test_pact.Test_an_author_with_id_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/clawlor/code/pact-testgen/test_app/provider/tests/test_pact.py", line 87, in test_test_an_author_deletion_request
    "/authors/1",
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/clawlor/code/pact-testgen/test_app/provider/library/views.py", line 58, in get_or_update_author
    return HttpResponse(status_code=204)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/django/http/response.py", line 329, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'status_code'

======================================================================
ERROR: test_test_an_author_update_request (tests.test_pact.Test_an_author_with_id_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/clawlor/code/pact-testgen/test_app/provider/tests/test_pact.py", line 81, in test_test_an_author_update_request
    success = verify_response("LibraryClient", "Library", expected, actual)
  File "/home/clawlor/code/pact-testgen/pact_testgen/verify.py", line 21, in verify_response
    verifier = ResponseVerifier(pactman_pact, pact_response.dict(exclude_none=True), result)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/pactman/verifier/verify.py", line 231, in __init__
    self.matching_rules = rule_matchers_v2(rules)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/pactman/verifier/matching_rule.py", line 334, in rule_matchers_v2
    section = split[1]
IndexError: list index out of range

======================================================================
ERROR: test_test_a_request_for_author_id_1 (tests.test_pact.Test_author_id_1_exists)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/clawlor/code/pact-testgen/test_app/provider/tests/test_pact.py", line 61, in test_test_a_request_for_author_id_1
    success = verify_response("LibraryClient", "Library", expected, actual)
  File "/home/clawlor/code/pact-testgen/pact_testgen/verify.py", line 21, in verify_response
    verifier = ResponseVerifier(pactman_pact, pact_response.dict(exclude_none=True), result)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/pactman/verifier/verify.py", line 231, in __init__
    self.matching_rules = rule_matchers_v2(rules)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/pactman/verifier/matching_rule.py", line 334, in rule_matchers_v2
    section = split[1]
IndexError: list index out of range

======================================================================
ERROR: test_test_a_book_search_request_for_a_non_existent_author (tests.test_pact.Test_nothing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/clawlor/code/pact-testgen/test_app/provider/tests/test_pact.py", line 41, in test_test_a_book_search_request_for_a_non_existent_author
    success = verify_response("LibraryClient", "Library", expected, actual)
  File "/home/clawlor/code/pact-testgen/pact_testgen/verify.py", line 22, in verify_response
    return verifier.verify(actual_response)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/pactman/verifier/verify.py", line 272, in verify
    if not self.check_rules(response.json(), self.body, ["body"]):
AttributeError: 'Response' object has no attribute 'json'

======================================================================
ERROR: test_test_an_author_creation_request (tests.test_pact.Test_nothing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/clawlor/code/pact-testgen/test_app/provider/tests/test_pact.py", line 27, in test_test_an_author_creation_request
    success = verify_response("LibraryClient", "Library", expected, actual)
  File "/home/clawlor/code/pact-testgen/pact_testgen/verify.py", line 21, in verify_response
    verifier = ResponseVerifier(pactman_pact, pact_response.dict(exclude_none=True), result)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/pactman/verifier/verify.py", line 231, in __init__
    self.matching_rules = rule_matchers_v2(rules)
  File "/home/clawlor/.virtualenvs/pact-testgen/lib/python3.7/site-packages/pactman/verifier/matching_rule.py", line 334, in rule_matchers_v2
    section = split[1]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 7 tests in 0.023s

FAILED (errors=6)
Destroying test database for alias 'default'...
```

**Comment by chrislawlor** [comment]
Fixed in b90344e61d2c0edfb1ff4ecf969cc55374ae8a11, c1a99823caea58d43a21ec299fe8fea482eaf9a6, and b0dd9ed3e22f88840fd9a813dc33eccd1beb5b92
